spring.application.name=smart-notes
server.port=8080

# Environment
spring.config.import=file:.env[.properties]

# Active Profile
spring.profiles.active=dev

# JWT Configuration
jwt.access-token.expiration-minutes=15
jwt.refresh-token.expiration-days=7

# JWT KeyStore Configuration
jwt.keystore.location=classpath:keys/jwt-keystore.jks
jwt.keystore.password=${JWT_KEYSTORE_PASSWORD}
jwt.key.password=${JWT_KEY_PASSWORD}

# JWT Key Rotation Configuration
jwt.signing.key.alias=jwtkey-2025
jwt.verification.key.aliases=jwtkey-2025