springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.url=/api-docs
springdoc.swagger-ui.tagsSorter=alpha

# Database Configuration for Development (Local MySQL)
spring.datasource.url=jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings for Development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# REDIS Configuration for Development (Local Redis - Docker)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Frontend URL for Local Development
app.frontend.url=http://localhost:3000

# Logging Level for Development
logging.level.com.be08=DEBUG